import datetime
import requests
import pandas as pd
import numpy as np

def fetch_historical_weather(latitude: float = 50.11, longitude: float = 8.68, start_date: str = "2026-01-01", end_date: str = "2026-08-01") -> pd.DataFrame:
    """fetches historical temperature, wind speed, and solar radiation"""
    #public open meteo ERA5 reanalysis archive endpoint
    url = "https://archive-api.open-meteo.com/v1/archive"

    #query parameters (default location is frankfurt am main)
    params = {
        "latitude": latitude,
        "longitude": longitude,
        "start_date": start_date,
        "end_date": end_date,
        "hourly": ["temperature_2m", "wind_speed_10m", "direct_radiation"],
        "timezone": "UTC"
    }

    #HTTP GET request
    resp = requests.get(url, params=params, timeout=15)
    resp.raise_for_status() #success check
    data = resp.json()["hourly"] #extract the nested hourly dictionary containing parallel data lists

    #construct the weather dataframe and parse the ISO timestamp strings to UTC
    df_weather = pd.DataFrame({
        "timestamp": pd.to_datetime(data["time"], utc=True),
        "temperature_c": data["temperature_2m"],
        "wind_speed_kmh": data["wind_speed_10m"],
        "solar_radiation_wm2": data["direct_radiation"]
    })

    #convert timestamp column to a datatimeindex for temporal merging and slicing
    df_weather.set_index("timestamp", inplace=True)
    return df_weather


def build_feature_dataset(df_prices: pd.DataFrame, df_weather: pd.DataFrame) -> pd.DataFrame:
    """joins prices with weather and extracts lag/temporal features"""
    #temporal data merging 
    df = df_prices.join(df_weather, how="inner")

    # calendar and cyclical Features
    df["hour"] = df.index.hour
    df["dayofweek"] = df.index.dayofweek
    df["is_weekend"] = (df["dayofweek"] >= 5).astype(int)
    df["month"] = df.index.month

    #sine/cosine encoding for cyclic hour of day
    df["hour_sin"] = np.sin(2 * np.pi * df["hour"] / 24.0)
    df["hour_cos"] = np.cos(2 * np.pi * df["hour"] / 24.0)

    #Autoaggressive lag features
    df["price_lag_24h"] = df["price_eur_mwh"].shift(24) #price yesterday
    df["price_lag_48h"] = df["price_eur_mwh"].shift(48) #same hour 2 days ago
    df["price_lag_168h"] = df["price_eur_mwh"].shift(168) # Same hour last week

    # rolling window statistics
    df["price_rolling_mean_24h"] = df["price_eur_mwh"].shift(24).rolling(window=24).mean()
    df["price_rolling_std_24h"] = df["price_eur_mwh"].shift(24).rolling(window=24).std()

    # drop NaN rows generated by shifts or lags
    df.dropna(inplace=True)
    return df